version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.11.11-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge